// Auto-generated Geography Database for Sri Lanka

export const SRI_LANKA_DISTRICTS: string[] = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya"
];

export const SRI_LANKA_CITIES: Record<string, string[]> = {
  "Ampara": [
    "Akkaraipattu",
    "Ambagahawatta",
    "Ampara",
    "Bakmitiyawa",
    "Deegawapiya",
    "Devalahinda",
    "Digamadulla Weeragoda",
    "Dorakumbura",
    "Gonagolla",
    "Hulannuge",
    "Irakkamam",
    "Kalmunai",
    "Kannakipuram",
    "Karativu",
    "Kekirihena",
    "Koknahara",
    "Kolamanthalawa",
    "Komari",
    "Lahugala",
    "Mahaoya",
    "Marathamune",
    "Namaloya",
    "Navithanveli",
    "Nintavur",
    "Oluvil",
    "Padiyatalawa",
    "Pahalalanda",
    "Panama",
    "Pannalagama",
    "Paragahakele",
    "Periyaneelavanai",
    "Polwaga Janapadaya",
    "Pottuvil",
    "Sainthamaruthu",
    "Samanthurai",
    "Serankada",
    "Tempitiya",
    "Thambiluvil",
    "Tirukovil",
    "Uhana",
    "Wadinagala",
    "Wanagamuwa"
  ],
  "Anuradhapura": [
    "Angamuwa",
    "Anuradhapura",
    "Awukana",
    "Bogahawewa",
    "Bulnewa",
    "Dematawewa",
    "Dimbulagala",
    "Dutuwewa",
    "Elayapattuwa",
    "Ellewewa",
    "Eppawala",
    "Etawatunuwewa",
    "Etaweeragollewa",
    "Galapitagala",
    "Galenbindunuwewa",
    "Galkadawala",
    "Galkiriyagama",
    "Galkulama",
    "Galnewa",
    "Gambirigaswewa",
    "Ganewalpola",
    "Gemunupura",
    "Getalawa",
    "Gnanikulama",
    "Gonahaddenawa",
    "Habarana",
    "Halmillawa Dambulla",
    "Halmillawetiya",
    "Hidogama",
    "Horawpatana",
    "Horiwila",
    "Hurigaswewa",
    "Hurulunikawewa",
    "Ihala Puliyankulama",
    "Ihalagama",
    "Ipologama",
    "Kagama",
    "Kahatagasdigiliya",
    "Kahatagollewa",
    "Kalakarambewa",
    "Kalaoya",
    "Kalawedi Ulpotha",
    "Kallanchiya",
    "Kalpitiya",
    "Kalukele Badanagala",
    "Kapugallawa",
    "Karagahawewa",
    "Kashyapapura",
    "Kebithigollewa",
    "Kebithigollewa",
    "Kekirawa",
    "Kendewa",
    "Kiralogama",
    "Kirigalwewa",
    "Kirimundalama",
    "Kitulhitiyawa",
    "Kurundankulama",
    "Labunoruwa",
    "Madatugama",
    "Maha Elagamuwa",
    "Mahabulankulama",
    "Mahailluppallama",
    "Mahakanadarawa",
    "Mahapothana",
    "Mahasenpura",
    "Mahawilachchiya",
    "Mailagaswewa",
    "Malwanagama",
    "Maneruwa",
    "Maradankadawala",
    "Maradankalla",
    "Medawachchiya",
    "Megodawewa",
    "Mihintale",
    "Morakewa",
    "Mulkiriyawa",
    "Muriyakadawala",
    "Nachchaduwa",
    "Namalpura",
    "Negampaha",
    "Nochchiyagama",
    "Nuwaragala",
    "Padavi Maithripura",
    "Padavi Parakramapura",
    "Padavi Sripura",
    "Padavi Sritissapura",
    "Padaviya",
    "Padikaramaduwa",
    "Pahala Halmillewa",
    "Pahala Maragahawe",
    "Pahalagama",
    "Palugaswewa",
    "Pandukabayapura",
    "Pandulagama",
    "Parakumpura",
    "Parangiyawadiya",
    "Parasangahawewa",
    "Pelatiyawa",
    "Pemaduwa",
    "Perimiyankulama",
    "Pihimbiyagolewa",
    "Pubbogama",
    "Punewa",
    "Rajanganaya",
    "Rambewa",
    "Rampathwila",
    "Rathmalgahawewa",
    "Saliyapura",
    "Seeppukulama",
    "Senapura",
    "Sivalakulama",
    "Siyambalewa",
    "Sravasthipura",
    "Talawa",
    "Tambuttegama",
    "Tammennawa",
    "Tantirimale",
    "Telhiriyawa",
    "Tirappane",
    "Tittagonewa",
    "Udunuwara Colony",
    "Upuldeniya",
    "Uttimaduwa",
    "Vellamanal",
    "Viharapalugama",
    "Wahalkada",
    "Wahamalgollewa",
    "Walagambahuwa",
    "Walahaviddawewa",
    "Welimuwapotana",
    "Welioya Project"
  ],
  "Colombo": [
    "Akarawita",
    "Aluth Mawatha Road",
    "Ambalangoda",
    "Anderson Plats",
    "Angampitiya",
    "Angulana",
    "Arawwala West",
    "Armour Street",
    "Arukwathupura",
    "Athurugiriya",
    "Avissawella",
    "Bambalapitiya",
    "Baseline Road",
    "Batawala",
    "Battaramulla",
    "Beddagana",
    "Biyagama",
    "Bokundara",
    "Bope",
    "Boralesgamuwa",
    "Borella",
    "Cinnamon Gardens",
    "Colombo 1",
    "Colombo 10",
    "Colombo 11",
    "Colombo 12",
    "Colombo 13",
    "Colombo 14",
    "Colombo 15",
    "Colombo 2",
    "Colombo 3",
    "Colombo 4",
    "Colombo 5",
    "Colombo 6",
    "Colombo 7",
    "Colombo 8",
    "Colombo 9",
    "Colombo General Hospital",
    "Colombo Kachcheri",
    "Colombo Labour Sec",
    "Colombo Secretariant",
    "Colpetty",
    "Dampe",
    "Dedigamuwa",
    "Dehiwala",
    "Deltara",
    "Dematagoda",
    "Egodauyana North",
    "Egodauyana South",
    "Fort",
    "Galawilawaththa",
    "Gem & Jewelry",
    "Godagama Junction",
    "Gorakapitiya",
    "Gothami Road",
    "Grandpass",
    "Gurulana",
    "Habarakada",
    "Hanwella",
    "Havelock Town",
    "Hiripitya",
    "Hokandara",
    "Homagama",
    "Homagama Town",
    "Horagala",
    "Hulftsdorp",
    "Indibedda",
    "Isurupaya",
    "Jayawardhenegama",
    "Kaduwela",
    "Kahathuduwa",
    "Kalapaluwawa",
    "Kaldemulla",
    "Kaluaggala",
    "Kandanapitiya",
    "Kapugoda",
    "Katubedda",
    "Katuwawala",
    "Kehelwatta",
    "Keppetipola Mawatha",
    "Kesbewa",
    "Kiriwattuduwa",
    "Kirulapone",
    "Kohuwala",
    "Kolonnawa",
    "Kopiyawatta",
    "Koralawella",
    "Kosgama",
    "Kotahena",
    "Kottawa",
    "Kottawa North",
    "Laksapatiya",
    "Liyanwala",
    "Lunawa",
    "Madapatha",
    "Madiwela",
    "Magammana-Dolekade",
    "Maharagama",
    "Makandana",
    "Malabe",
    "Malabe",
    "Malagala",
    "Malapalla",
    "Maligakanda",
    "Maligawatta",
    "Maradana",
    "Mattegoda",
    "Meepe Junction",
    "Melle Street",
    "Miraniya Street",
    "Mirihana",
    "Mirihana North",
    "Modara",
    "Moratumulla",
    "Moratuwa",
    "Mount Lavinia",
    "Mullegama",
    "Mutwal South",
    "Nagalagam Street",
    "Napawela",
    "Narahenpita",
    "National Museum of Colombo",
    "Nawala",
    "Nawala-Koswatte",
    "Nawinna",
    "Nugegoda",
    "Obeysekarapura",
    "Oruwala",
    "Padukka",
    "Pamunuwa-Patiragoda",
    "Panagoda",
    "Panagoda Army Camp",
    "Panchikawatte",
    "Pannipitiya",
    "Parliament of Sri Lanka",
    "Pelenwatta",
    "Pepiliyana",
    "Pettah",
    "Pettah Bus Stand",
    "Piliyandala",
    "Pinnawala-Waga",
    "Pitipana Homagama",
    "Polgasowita",
    "Polhengoda",
    "Poregedara",
    "Pugoda",
    "Rajagiriya",
    "Ranala",
    "Ratmalana",
    "Ratmalana North",
    "Rawathawatta",
    "Rifel Street",
    "Rukmale-Pannipitiya",
    "Sarasavipaya",
    "Sethsiripaya",
    "Siddamulla",
    "Sirimal Uyana",
    "Siyambalagoda",
    "Slave Island",
    "Sri Jayawardenepura",
    "Sri Perakumpura",
    "St. Anthony's",
    "Sudanapura",
    "Suwarapola",
    "Talangama North",
    "Talangama South",
    "Talawatugoda",
    "Torington Square",
    "Tummodara",
    "Udahamulla",
    "Udugamkanda",
    "University of Colombo",
    "Vidyodaya University",
    "Waga",
    "Wanathamulla",
    "Wasala Road",
    "Wellawatta",
    "Willorawatta",
    "Wolfendal Street"
  ],
  "Badulla": [
    "Akkarasiyaya",
    "Aluketiyawa",
    "Aluttaramma",
    "Ambadandegama",
    "Ambagasdowa",
    "Arawa",
    "Arawakumbura",
    "Arawatta",
    "Atakiriya",
    "Badulla",
    "Baduluoya",
    "Ballaketuwa",
    "Bambarapana",
    "Bandarawela",
    "Beramada",
    "Bibilegama",
    "Boragas",
    "Boralanda",
    "Bowela",
    "Central Camp",
    "Damanewela",
    "Dambana",
    "Dehiattakandiya",
    "Demodara",
    "Diganatenna",
    "Dikkapitiya",
    "Dimbulana",
    "Divulapelessa",
    "Diyatalawa",
    "Dulgolla",
    "Ekiriyankumbura",
    "Ella",
    "Ettampitiya",
    "Galauda",
    "Galporuyaya",
    "Gawarawela",
    "Girandurukotte",
    "Godunna",
    "Gurutalawa",
    "Haldummulla",
    "Hali Ela",
    "Hangunnawa",
    "Haputale",
    "Hebarawa",
    "Heeloya",
    "Helahalpe",
    "Helapupula",
    "Hopton",
    "Idalgashinna",
    "Idalgashinna",
    "Kahataruppa",
    "Kalugahakandura",
    "Kalupahana",
    "Kebillawela",
    "Kendagolla",
    "Keselpotha",
    "Ketawatta",
    "Kiriwanagama",
    "Koslanda",
    "Kuruwitenna",
    "Kuttiyagolla",
    "Landewela",
    "Liyangahawela",
    "Lunugala",
    "Lunuwatta",
    "Madulsima",
    "Mahiyanganaya",
    "Makulella",
    "Malgoda",
    "Mapakadawewa",
    "Maspanna",
    "Maussagolla",
    "Mawanagama",
    "Medawela Udukinda",
    "Meegahakiula",
    "Metigahatenna",
    "Mirahawatta",
    "Miriyabedda",
    "Nawamedagama",
    "Nelumgama",
    "Nikapotha",
    "Nugatalawa",
    "Ohiya",
    "Pahalarathkinda",
    "Pallekiruwa",
    "Passara",
    "Pattiyagedara",
    "Pelagahatenna",
    "Perawella",
    "Pitamaruwa",
    "Pitapola",
    "Puhulpola",
    "Rajagalatenna",
    "Rathkarawwa",
    "Ridimaliyadda",
    "Silmiyapura",
    "Sirimalgoda",
    "Siripura",
    "Sorabora Colony",
    "Soragune",
    "Soranathota",
    "Taldena",
    "Timbirigaspitiya",
    "Uduhawara",
    "Uraniya",
    "Uva Karandagolla",
    "Uva Mawelagama",
    "Uva Tenna",
    "Uva Tissapura",
    "Welimada",
    "Weranketagoda",
    "Wewatta",
    "Wineethagama",
    "Yalagamuwa",
    "Yalwela"
  ],
  "Batticaloa": [
    "Addalaichenai",
    "Ampilanthurai",
    "Araipattai",
    "Ayithiyamalai",
    "Bakiella",
    "Batticaloa",
    "Cheddipalayam",
    "Chenkaladi",
    "Eravur",
    "Kaluwanchikudi",
    "Kaluwankemy",
    "Kannankudah",
    "Karadiyanaru",
    "Kathiraveli",
    "Kattankudi",
    "Kiran",
    "Kirankulam",
    "Koddaikallar",
    "Kokkaddicholai",
    "Kurukkalmadam",
    "Mandur",
    "Miravodai",
    "Murakottanchanai",
    "Navagirinagar",
    "Navatkadu",
    "Oddamavadi",
    "Palamunai",
    "Pankudavely",
    "Periyaporativu",
    "Periyapullumalai",
    "Pillaiyaradi",
    "Punanai",
    "Thannamunai",
    "Thettativu",
    "Thikkodai",
    "Thirupalugamam",
    "Unnichchai",
    "Vakaneri",
    "Vakarai",
    "Valaichenai",
    "Vantharumoolai",
    "Vellavely"
  ],
  "Galle": [
    "Agaliya",
    "Ahangama",
    "Ahungalla",
    "Akmeemana",
    "Alawatugoda",
    "Aluthwala",
    "Ampegama",
    "Amugoda",
    "Anangoda",
    "Angulugaha",
    "Ankokkawala",
    "Aselapura",
    "Baddegama",
    "Balapitiya",
    "Banagala",
    "Batapola",
    "Bentota",
    "Boossa",
    "Dellawa",
    "Dikkumbura",
    "Dodanduwa",
    "Ella Tanabaddegama",
    "Elpitiya",
    "Galle",
    "Ginimellagaha",
    "Gintota",
    "Godahena",
    "Gonamulla Junction",
    "Gonapinuwala",
    "Habaraduwa",
    "Haburugala",
    "Hikkaduwa",
    "Hiniduma",
    "Hiyare",
    "Kahaduwa",
    "Kahawa",
    "Karagoda",
    "Karandeniya",
    "Kosgoda",
    "Kottawagama",
    "Kottegoda",
    "Kuleegoda",
    "Magedara",
    "Mahawela Sinhapura",
    "Mapalagama",
    "Mapalagama Central",
    "Mattaka",
    "Meda-Keembiya",
    "Meetiyagoda",
    "Nagoda",
    "Nakiyadeniya",
    "Nawandagala",
    "Neluwa",
    "Nindana",
    "Pahala Millawa",
    "Panangala",
    "Pannimulla Panagoda",
    "Parana Thanayamgoda",
    "Patana",
    "Pitigala",
    "Poddala",
    "Polgampola",
    "Porawagama",
    "Rantotuwila",
    "Talagampola",
    "Talgaspe",
    "Talpe",
    "Tawalama",
    "Tiranagama",
    "Udalamatta",
    "Udugama",
    "Uluvitike",
    "Unawatuna",
    "Unawitiya",
    "Uragaha",
    "Uragasmanhandiya",
    "Wakwella",
    "Walahanduwa",
    "Wanchawela",
    "Wanduramba",
    "Warukandeniya",
    "Watugedara",
    "Weihena",
    "Welikanda",
    "Wilanagama",
    "Yakkalamulla",
    "Yatalamatta"
  ],
  "Gampaha": [
    "Akaragama",
    "Ambagaspitiya",
    "Ambepussa",
    "Andiambalama",
    "Attanagalla",
    "Badalgama",
    "Banduragoda",
    "Batuwatta",
    "Bemmulla",
    "Biyagama IPZ",
    "Bokalagama",
    "Bollete (WP)",
    "Bopagama",
    "Buthpitiya",
    "Dagonna",
    "Danowita",
    "Debahera",
    "Dekatana",
    "Delgoda",
    "Delwagura",
    "Demalagama",
    "Demanhandiya",
    "Dewalapola",
    "Divulapitiya",
    "Divuldeniya",
    "Dompe",
    "Dunagaha",
    "Ekala",
    "Ellakkala",
    "Essella",
    "Galedanda",
    "Gampaha",
    "Ganemulla",
    "Giriulla",
    "Gonawala",
    "Halpe",
    "Hapugastenna",
    "Heiyanthuduwa",
    "Hinatiyana Madawala",
    "Hiswella",
    "Horampella",
    "Hunumulla",
    "Hunupola",
    "Ihala Madampella",
    "Imbulgoda",
    "Ja-Ela",
    "Kadawatha",
    "Kahatowita",
    "Kalagedihena",
    "Kaleliya",
    "Kandana",
    "Katana",
    "Katudeniya",
    "Katunayake",
    "Katunayake Air Force Camp",
    "Katunayake(FTZ)",
    "Katuwellegama",
    "Kelaniya",
    "Kimbulapitiya",
    "Kirindiwela",
    "Kitalawalana",
    "Kochchikade",
    "Kotadeniyawa",
    "Kotugoda",
    "Kumbaloluwa",
    "Loluwagoda",
    "Mabodale",
    "Mabola",
    "Madelgamuwa",
    "Makewita",
    "Makola",
    "Malwana",
    "Mandawala",
    "Marandagahamula",
    "Mellawagedara",
    "Minuwangoda",
    "Mirigama",
    "Miriswatta",
    "Mithirigala",
    "Muddaragama",
    "Mudungoda",
    "Mulleriyawa New Town",
    "Naranwala",
    "Nawana",
    "Nedungamuwa",
    "Negombo",
    "Nikadalupotha",
    "Nikahetikanda",
    "Nittambuwa",
    "Niwandama",
    "Opatha",
    "Pamunugama",
    "Pamunuwatta",
    "Panawala",
    "Pasyala",
    "Peliyagoda",
    "Pepiliyawala",
    "Pethiyagoda",
    "Polpithimukulana",
    "Puwakpitiya",
    "Radawadunna",
    "Radawana",
    "Raddolugama",
    "Ragama",
    "Ruggahawila",
    "Seeduwa",
    "Siyambalape",
    "Talahena",
    "Thambagalla",
    "Thimbirigaskatuwa",
    "Tittapattara",
    "Udathuthiripitiya",
    "Udugampola",
    "Uggalboda",
    "Urapola",
    "Uswetakeiyawa",
    "Veyangoda",
    "Walgammulla",
    "Walpita",
    "Walpola (WP)",
    "Wathurugama",
    "Watinapaha",
    "Wattala",
    "Wattala",
    "Weboda",
    "Wegowwa",
    "Weweldeniya",
    "Yakkala",
    "Yatiyana"
  ],
  "Hambantota": [
    "Ambalantota",
    "Angunakolapelessa",
    "Angunakolawewa",
    "Bandagiriya Colony",
    "Barawakumbuka",
    "Beliatta",
    "Beragama",
    "Beralihela",
    "Bundala",
    "Ellagala",
    "Gangulandeniya",
    "Gangulandeniya",
    "Getamanna",
    "Goda Koggalla",
    "Gonagamuwa Uduwila",
    "Gonnoruwa",
    "Hakuruwela",
    "Hambantota",
    "Handugala",
    "Hungama",
    "Ihala Beligalla",
    "Iththa Demaliya",
    "Julampitiya",
    "Kahandamodara",
    "Kariyamaditta",
    "Katuwana",
    "Kawantissapura",
    "Kirama",
    "Kirinda",
    "Lunama",
    "Lunugamwehera",
    "Magama",
    "Mahagalwewa",
    "Mamadala",
    "Medamulana",
    "Meegahajandura",
    "Middeniya",
    "Modarawana",
    "Mulkirigala",
    "Nakulugamuwa",
    "Netolpitiya",
    "Nihiluwa",
    "Padawkema",
    "Pahala Andarawewa",
    "Rammalawarapitiya",
    "Ranakeliya",
    "Ranmuduwewa",
    "Ranna",
    "Ratmalwala",
    "Ruhunu Ridiyagama",
    "Sooriyawewa Town",
    "Tangalla",
    "Tissamaharama",
    "Uda Gomadiya",
    "Udamattala",
    "Uswewa",
    "Vitharandeniya",
    "Walasmulla",
    "Weeraketiya",
    "Weerawila",
    "Weerawila NewTown",
    "Wekandawela",
    "Weligatta",
    "Yatigala"
  ],
  "Jaffna": [
    "Allaipiddi",
    "Allaveddi",
    "Alvai",
    "Anaikoddai",
    "Analaitivu",
    "Araly",
    "Atchuveli",
    "Chankanai",
    "Chavakachcheri",
    "Chullipuram",
    "Chundikuli",
    "Chunnakam",
    "Delft",
    "Delft West",
    "Eluvaitivu",
    "Erialai",
    "Gurunagar",
    "Ilavalai",
    "Jaffna",
    "Kaitadi",
    "Kankesanthurai",
    "Karainagar",
    "Karaveddi",
    "Kayts",
    "Kodikamam",
    "Kokuvil",
    "Kondavil",
    "Kopay",
    "Kudatanai",
    "Mahiyampathy",
    "Mallakam",
    "Mandaitivu",
    "Manipay",
    "Mathagal",
    "Meesalai",
    "Mirusuvil",
    "Nagarkovil",
    "Nagendramadam",
    "Nainathivu",
    "Nallur",
    "Neervely",
    "Pandaterippu",
    "Point Pedro",
    "Puloly",
    "Pungudutivu",
    "Puttur",
    "Sandilipay",
    "Sangarathai",
    "Sithankerny",
    "Sivankovilady",
    "Thellippallai",
    "Thirunelvely",
    "Thondamanaru",
    "Urumpirai",
    "Vaddukoddai",
    "Valvettithurai",
    "Vannarponnai",
    "Varany",
    "Vasavilan",
    "Velanai"
  ],
  "Kalutara": [
    "Agalawatta",
    "Alubomulla",
    "Anguruwatota",
    "Atale",
    "Baduraliya",
    "Bandaragama",
    "Batugampola",
    "Bellana",
    "Beruwala",
    "Bolossagama",
    "Bombuwala",
    "Boralugoda",
    "Bulathsinhala",
    "Danawala Thiniyawala",
    "Delmella",
    "Dharga Town",
    "Diwalakada",
    "Dodangoda",
    "Dombagoda",
    "Ethkandura",
    "Galpatha",
    "Gamagoda",
    "Gonagalpura",
    "Gonapola Junction",
    "Govinna",
    "Gurulubadda",
    "Halkandawila",
    "Haltota",
    "Halvitigala Colony",
    "Halwala",
    "Halwatura",
    "Handapangoda",
    "Hedigalla Colony",
    "Henegama",
    "Hettimulla",
    "Horana",
    "Ihalahewessa",
    "Induruwa",
    "Ingiriya",
    "Ittapana",
    "Kahawala",
    "Kalawila Kiranthidiya",
    "Kalutara",
    "Kananwila",
    "Kandanagama",
    "Kelinkanda",
    "Kitulgoda",
    "Koholana",
    "Kuda Uduwa",
    "Labbala",
    "Maggona",
    "Mahagama",
    "Mahakalupahana",
    "Maharangalla",
    "Malgalla Talangalla",
    "Matugama",
    "Meegahatenna",
    "Meegama",
    "Meegoda",
    "Millaniya",
    "Millewa",
    "Miwanapalana",
    "Molkawa",
    "Morapitiya",
    "Morontuduwa",
    "Nawattuduwa",
    "Neboda",
    "Padagoda",
    "Pahalahewessa",
    "Paiyagala",
    "Panadura",
    "Pannala",
    "Paragastota",
    "Paragoda",
    "Paraigama",
    "Pelanda",
    "Pelawatta",
    "Pimbura",
    "Pitagaldeniya",
    "Pokunuwita",
    "Poruwedanda",
    "Ratmale",
    "Remunagoda",
    "Talgaswela",
    "Tebuwana",
    "Uduwara",
    "Utumgama",
    "Veyangalla",
    "Wadduwa",
    "Walagedara",
    "Walallawita",
    "Waskaduwa",
    "Welipenna",
    "Weliveriya",
    "Welmilla Junction",
    "Weragala",
    "Yagirala",
    "Yatadolawatta",
    "Yatawara Junction"
  ],
  "Kandy": [
    "Akurana",
    "Aludeniya",
    "Ambagahapelessa",
    "Ambagamuwa Udabulathgama",
    "Ambatenna",
    "Ampitiya",
    "Ankumbura",
    "Atabage",
    "Balana",
    "Bambaragahaela",
    "Batagolladeniya",
    "Batugoda",
    "Batumulla",
    "Bawlana",
    "Bopana",
    "Danture",
    "Dedunupitiya",
    "Dekinda",
    "Deltota",
    "Divulankadawala",
    "Dolapihilla",
    "Dolosbage",
    "Dunuwila",
    "Etulgama",
    "Galaboda",
    "Galagedara",
    "Galaha",
    "Galhinna",
    "Gampola",
    "Gelioya",
    "Godamunna",
    "Gomagoda",
    "Gonagantenna",
    "Gonawalapatana",
    "Gunnepana",
    "Gurudeniya",
    "Hakmana",
    "Handaganawa",
    "Handawalapitiya",
    "Handessa",
    "Harangalagama",
    "Hataraliyadda",
    "Hindagala",
    "Hondiyadeniya",
    "Hunnasgiriya",
    "Ihala Kobbekaduwa",
    "Inguruwatta",
    "Jambugahapitiya",
    "Kadugannawa",
    "Kahataliyadda",
    "Kalugala",
    "Kandy",
    "Kapuliyadde",
    "Katugastota",
    "Katukitula",
    "Kelanigama",
    "Kengalla",
    "Ketaboola",
    "Ketakumbura",
    "Kobonila",
    "Kolabissa",
    "Kolongoda",
    "Kulugammana",
    "Kumbukkandura",
    "Kumburegama",
    "Kundasale",
    "Leemagahakotuwa",
    "Lunugama",
    "Lunuketiya Maditta",
    "Madawala Bazaar",
    "Madawalalanda",
    "Madugalla",
    "Madulkele",
    "Mahadoraliyadda",
    "Mahamedagama",
    "Mahanagapura",
    "Mailapitiya",
    "Makkanigama",
    "Makuldeniya",
    "Mangalagama",
    "Mapakanda",
    "Marassana",
    "Mawatura",
    "Medamahanuwara",
    "Medawala Harispattuwa",
    "Meetalawa",
    "Megoda Kalugamuwa",
    "Menikdiwela",
    "Menikhinna",
    "Mimure",
    "Minigamuwa",
    "Minipe",
    "Moragahapallama",
    "Murutalawa",
    "Muruthagahamulla",
    "Nanuoya",
    "Naranpanawa",
    "Narawelpita",
    "Nawalapitiya",
    "Nawathispane",
    "Nillambe",
    "Nugaliyadda",
    "Ovilikanda",
    "Pallekotuwa",
    "Panwilatenna",
    "Paradeka",
    "Pasbage",
    "Pattitalawa",
    "Peradeniya",
    "Pilimatalawa",
    "Poholiyadda",
    "Pubbiliya",
    "Pupuressa",
    "Pussellawa",
    "Putuhapuwa",
    "Rajawella",
    "Rambukpitiya",
    "Rambukwella",
    "Rangala",
    "Rantembe",
    "Sangarajapura",
    "Senarathwela",
    "Talatuoya",
    "Teldeniya",
    "Tennekumbura",
    "Uda Peradeniya",
    "Udahentenna",
    "Udatalawinna",
    "Udispattuwa",
    "Ududumbara",
    "Uduwahinna",
    "Uduwela",
    "Ulapane",
    "Unuwinna",
    "Velamboda",
    "Watagoda",
    "Watagoda Harispattuwa",
    "Wattappola",
    "Weligampola",
    "Wendaruwa",
    "Weragantota",
    "Werapitya",
    "Werellagama",
    "Wettawa",
    "Yahalatenna",
    "Yatihalagala"
  ],
  "Nuwara Eliya": [
    "Agarapathana",
    "Ambatalawa",
    "Ambewela",
    "Bogawantalawa",
    "Bopattalawa",
    "Dagampitiya",
    "Dayagama Bazaar",
    "Dikoya",
    "Doragala",
    "Dunukedeniya",
    "Egodawela",
    "Ekiriya",
    "Elamulla",
    "Ginigathena",
    "Gonakele",
    "Haggala",
    "Halgranoya",
    "Hangarapitiya",
    "Hanguranketha",
    "Hapugasthalawa",
    "Harasbedda",
    "Hatton",
    "Hewaheta",
    "Hitigegama",
    "Jangulla",
    "Kalaganwatta",
    "Kandapola",
    "Karandagolla",
    "Keerthi Bandarapura",
    "Kiribathkumbura",
    "Kotiyagala",
    "Kotmale",
    "Kottellena",
    "Kumbalgamuwa",
    "Kumbukwela",
    "Kurupanawela",
    "Labukele",
    "Laxapana",
    "Lindula",
    "Madulla",
    "Mandaram Nuwara",
    "Marymount Colony",
    "Maskeliya",
    "Maswela",
    "Maturata",
    "Mipanawa",
    "Mipilimana",
    "Morahenagama",
    "Munwatta",
    "Nayapana Janapadaya",
    "Nildandahinna",
    "Nissanka Uyana",
    "Norwood",
    "Nuwara Eliya",
    "Padiyapelella",
    "Pallebowala",
    "Panvila",
    "Pitawala",
    "Pundaluoya",
    "Ramboda",
    "Rikillagaskada",
    "Rozella",
    "Rupaha",
    "Ruwaneliya",
    "Santhipura",
    "Talawakele",
    "Tawalantenna",
    "Teripeha",
    "Udamadura",
    "Udapussallawa",
    "Uva Deegalla",
    "Uva Uduwara",
    "Uvaparanagama",
    "Walapane",
    "Watawala",
    "Widulipura",
    "Wijebahukanda"
  ],
  "Kegalle": [
    "Alawala",
    "Alawatura",
    "Alawwa",
    "Algama",
    "Alutnuwara",
    "Ambalakanda",
    "Ambulugala",
    "Amitirigala",
    "Ampagala",
    "Anhandiya",
    "Anhettigama",
    "Aranayaka",
    "Aruggammana",
    "Batuwita",
    "Beligala(Sab)",
    "Belihuloya",
    "Berannawa",
    "Bopitiya",
    "Bopitiya (SAB)",
    "Boralankada",
    "Bossella",
    "Bulathkohupitiya",
    "Damunupola",
    "Debathgama",
    "Dedugala",
    "Deewala Pallegama",
    "Dehiowita",
    "Deldeniya",
    "Deloluwa",
    "Deraniyagala",
    "Dewalegama",
    "Dewanagala",
    "Dombemada",
    "Dorawaka",
    "Dunumala",
    "Galapitamada",
    "Galatara",
    "Galigamuwa Town",
    "Gallella",
    "Galpatha(Sab)",
    "Gantuna",
    "Getahetta",
    "Godagampola",
    "Gonagala",
    "Hakahinna",
    "Hakbellawaka",
    "Halloluwa",
    "Hedunuwewa",
    "Hemmatagama",
    "Hewadiwela",
    "Hingula",
    "Hinguralakanda",
    "Hingurana",
    "Hiriwadunna",
    "Ihala Walpola",
    "Ihalagama",
    "Imbulana",
    "Imbulgasdeniya",
    "Kabagamuwa",
    "Kahapathwala",
    "Kandaketya",
    "Kannattota",
    "Karagahinna",
    "Kegalle",
    "Kehelpannala",
    "Ketawala Leula",
    "Kitulgala",
    "Kondeniya",
    "Kotiyakumbura",
    "Lewangama",
    "Mahabage",
    "Makehelwala",
    "Malalpola",
    "Maldeniya",
    "Maliboda",
    "Maliyadda",
    "Malmaduwa",
    "Marapana",
    "Mawanella",
    "Meetanwala",
    "Migastenna Sabara",
    "Miyanawita",
    "Molagoda",
    "Morontota",
    "Narangala",
    "Narangoda",
    "Nattarampotha",
    "Nelundeniya",
    "Niyadurupola",
    "Noori",
    "Pannila",
    "Pattampitiya",
    "Pilawala",
    "Pothukoladeniya",
    "Puswelitenna",
    "Rambukkana",
    "Rilpola",
    "Rukmale",
    "Ruwanwella",
    "Samanalawewa",
    "Seaforth Colony",
    "Spring Valley",
    "Talgaspitiya",
    "Teligama",
    "Tholangamuwa",
    "Thotawella",
    "Udaha Hawupe",
    "Udapotha",
    "Uduwa",
    "Undugoda",
    "Ussapitiya",
    "Wahakula",
    "Waharaka",
    "Wanaluwewa",
    "Warakapola",
    "Watura",
    "Weeoya",
    "Wegalla",
    "Weligalla",
    "Welihelatenna",
    "Wewelwatta",
    "Yatagama",
    "Yatapana",
    "Yatiyantota",
    "Yattogoda"
  ],
  "Kilinochchi": [
    "Akkarayankulam",
    "Aliyawalai",
    "Ambalnagar",
    "Cheddiyakurichchi",
    "Chempiyanpattu",
    "Chundikulam",
    "Elephant Pass",
    "Eluthumadduval",
    "Iranaitiv",
    "Iyyakachchi",
    "Kalmadunagar",
    "Kandavalai",
    "Karachchi",
    "Karadipokku",
    "Kavutharimunai",
    "Kilay",
    "Kilinochchi",
    "Konavil",
    "Kunchuparanthan",
    "Muhamalai",
    "Mulliyan",
    "Murasumoddai",
    "Pachchilaipalli",
    "Pallai",
    "Pallavarayankaddu",
    "Paranthan",
    "Poonakary",
    "Puliyampokkanai",
    "Punakari-Nallur",
    "Ramanathapuram",
    "Sivanagar",
    "Sivapuram",
    "Skanthapuram",
    "Soranpattu",
    "Thalaiyadi",
    "Tharmapuram",
    "Thirunagar",
    "Thiruvaiaru",
    "Uruthirapuram",
    "Vaddakachchi",
    "Vannerikkulam",
    "Veravil",
    "Vinayagapuram"
  ],
  "Kurunegala": [
    "Alahengama",
    "Alahitiyawa",
    "Ambakote",
    "Ambanpola",
    "Andiyagala",
    "Anukkane",
    "Aragoda",
    "Ataragalla",
    "Awulegama",
    "Balalla",
    "Bamunukotuwa",
    "Bandara Koswatta",
    "Bingiriya",
    "Bogamulla",
    "Boraluwewa",
    "Boyagane",
    "Bujjomuwa",
    "Buluwala",
    "Dadayamtalawa",
    "Dambadeniya",
    "Daraluwa",
    "Deegalla",
    "Demataluwa",
    "Demuwatha",
    "Diddeniya",
    "Digannewa",
    "Divullegoda",
    "Diyasenpura",
    "Dodangaslanda",
    "Doluwa",
    "Doragamuwa",
    "Doratiyawa",
    "Dunumadalawa",
    "Dunuwilapitiya",
    "Ehetuwewa",
    "Elibichchiya",
    "Embogama",
    "Etungahakotuwa",
    "Galadivulwewa",
    "Galgamuwa",
    "Gallellagama",
    "Gallewa",
    "Ganegoda",
    "Girathalana",
    "Gokaralla",
    "Gonawila",
    "Halmillawewa",
    "Handungamuwa",
    "Harankahawa",
    "Helamada",
    "Hengamuwa",
    "Hettipola",
    "Hewainna",
    "Hilogama",
    "Hindagolla",
    "Hiriyala Lenawa",
    "Hiruwalpola",
    "Horambawa",
    "Hulogedara",
    "Hulugalla",
    "Ibbagamuwa",
    "Ihala Gomugomuwa",
    "Ihala Kadigamuwa",
    "Ihala Katugampala",
    "Illagolla",
    "Ilukhena",
    "Indulgodakanda",
    "Ithanawatta",
    "Kadigawa",
    "Kalankuttiya",
    "Kalatuwawa",
    "Kalugamuwa",
    "Kanadeniyawala",
    "Kanattewewa",
    "Kandegedara",
    "Karagahagedara",
    "Karambe",
    "Katiyawa",
    "Katupota",
    "Kawudulla",
    "Kawuduluwewa Stagell",
    "Kekunagolla",
    "Keppitiwalana",
    "Kimbulwanaoya",
    "Kirimetiyawa",
    "Kirindawa",
    "Kirindigalla",
    "Kithalawa",
    "Kitulwala",
    "Kobeigane",
    "Kohilagedara",
    "Konwewa",
    "Kosdeniya",
    "Kosgolla",
    "Kotagala",
    "Kotawehera",
    "Kudagalgamuwa",
    "Kudakatnoruwa",
    "Kuliyapitiya",
    "Kumaragama",
    "Kumbukgeta",
    "Kumbukwewa",
    "Kuratihena",
    "Kurunegala",
    "Lihiriyagama",
    "Lonahettiya",
    "Madahapola",
    "Madakumburumulla",
    "Madalagama",
    "Madawala Ulpotha",
    "Maduragoda",
    "Maeliya",
    "Magulagama",
    "Maha Ambagaswewa",
    "Mahagalkadawala",
    "Mahagirilla",
    "Mahamukalanyaya",
    "Mahananneriya",
    "Mahapallegama",
    "Maharachchimulla",
    "Mahatalakolawewa",
    "Mahawewa",
    "Maho",
    "Makulewa",
    "Makulpotha",
    "Makulwewa",
    "Malagane",
    "Mandapola",
    "Maspotha",
    "Mawathagama",
    "Medirigiriya",
    "Medivawa",
    "Meegalawa",
    "Meegaswewa",
    "Meewellawa",
    "Melsiripura",
    "Metikumbura",
    "Metiyagane",
    "Minhettiya",
    "Minuwangete",
    "Mirihanagama",
    "Monnekulama",
    "Moragane",
    "Moragollagama",
    "Morathiha",
    "Munamaldeniya",
    "Muruthenge",
    "Mutugala",
    "Nabadewa",
    "Nagollagama",
    "Nagollagoda",
    "Nakkawatta",
    "Narammala",
    "Nawasenapura",
    "Nawatalwatta",
    "Nelliya",
    "Nikaweratiya",
    "Nugagolla",
    "Nugawela",
    "Padeniya",
    "Padiwela",
    "Pahalagiribawa",
    "Pahamune",
    "Palagala",
    "Palapathwela",
    "Palaviya",
    "Pallewela",
    "Palukadawala",
    "Panadaragama",
    "Panagamuwa",
    "Panaliya",
    "Panapitiya",
    "Panliyadda",
    "Pansiyagama",
    "Parape",
    "Pathanewatta",
    "Pattiya Watta",
    "Perakanatta",
    "Periyakadneluwa",
    "Pihimbiya Ratmale",
    "Pihimbuwa",
    "Pilessa",
    "Polgahawela",
    "Polgolla",
    "Polpithigama",
    "Pothuhera",
    "Pothupitiya",
    "Pujapitiya",
    "Rakwana",
    "Ranorawa",
    "Rathukohodigala",
    "Ridibendiella",
    "Ridigama",
    "Saliya Asokapura",
    "Sandalankawa",
    "Sevanapitiya",
    "Sirambiadiya",
    "Sirisetagama",
    "Siyambalangamuwa",
    "Siyambalawewa",
    "Solepura",
    "Solewewa",
    "Sunandapura",
    "Talawattegedara",
    "Tambutta",
    "Tennepanguwa",
    "Thalahitimulla",
    "Thalakolawewa",
    "Thalwita",
    "Tharana Udawela",
    "Thimbiriyawa",
    "Thorayaya",
    "Tisogama",
    "Tulhiriya",
    "Tuntota",
    "Tuttiripitigama",
    "Udagaldeniya",
    "Udahingulwala",
    "Udawatta",
    "Udubaddawa",
    "Udumulla",
    "Uhumiya",
    "Ulpotha Pallekele",
    "Ulpothagama",
    "Usgala Siyabmalangamuwa",
    "Vijithapura",
    "Wadakada",
    "Wadumunnegedara",
    "Walakumburumulla",
    "Wannigama",
    "Wannikudawewa",
    "Wannilhalagama",
    "Wannirasnayakapura",
    "Warawewa",
    "Wariyapola",
    "Watareka",
    "Wattegama",
    "Watuwatta",
    "Weerapokuna",
    "Welawa Juncton",
    "Welipennagahamulla",
    "Wellagala",
    "Wellarawa",
    "Wellawa",
    "Welpalla",
    "Wennoruwa",
    "Weuda",
    "Wewagama",
    "Wilgamuwa",
    "Yakwila",
    "Yatigaloluwa"
  ],
  "Mannar": [
    "Aandankulam",
    "Adampan",
    "Arippu",
    "Athimottai",
    "Chilavathurai",
    "Erukkalampiddy",
    "Illuppaikadavai",
    "Karisal",
    "Kokkupadayan",
    "Madhu Church",
    "Madhu Road",
    "Mannar",
    "Marichchikaddi",
    "Mullikulam",
    "Murunkan",
    "Nanattan",
    "Palampiddy",
    "Pallimunai",
    "Pandaraveli",
    "Pappamoddai",
    "Parappankandal",
    "Parappukadanthan",
    "Periyakunchikulam",
    "Periyamadhu",
    "Periyapandivirichchan",
    "Pesalai",
    "Potkerny",
    "Puthukudiyiruppu",
    "Puthuveli",
    "Sooriyakaddaikadhu",
    "Thalaimannar",
    "Thalaimannar Pier",
    "Thalaimannar West",
    "Thalvupadu",
    "Tharapuram",
    "Thiruketheeswaram",
    "Uyilankulam",
    "Uyirtharasankulam",
    "Vaddakandal",
    "Vankalai",
    "Vellankulam",
    "Veppankulam",
    "Vidataltivu"
  ],
  "Matale": [
    "Akuramboda",
    "Alawatuwala",
    "Alwatta",
    "Ambana",
    "Aralaganwila",
    "Ataragallewa",
    "Bambaragaswewa",
    "Barawardhana Oya",
    "Beligamuwa",
    "Damana",
    "Dambulla",
    "Damminna",
    "Dankanda",
    "Delwite",
    "Devagiriya",
    "Dewahuwa",
    "Divuldamana",
    "Dullewa",
    "Dunkolawatta",
    "Elkaduwa",
    "Erawula Junction",
    "Etanawala",
    "Galewela",
    "Galoya Junction",
    "Gammaduwa",
    "Gangala Puwakpitiya",
    "Hasalaka",
    "Hattota Amuna",
    "Ihala Halmillewa",
    "Illukkumbura",
    "Imbulgolla",
    "Inamaluwa",
    "Iriyagolla",
    "Kaikawala",
    "Kalundawa",
    "Kandalama",
    "Kavudupelella",
    "Kibissa",
    "Kiwula",
    "Kongahawela",
    "Laggala Pallegama",
    "Leliambe",
    "Lenadora",
    "Madipola",
    "Madipola",
    "Mahawela",
    "Mananwatta",
    "Maraka",
    "Matale",
    "Melipitiya",
    "Metihakka",
    "Millawana",
    "Muwandeniya",
    "Nalanda",
    "Naula",
    "Opalgala",
    "Pallepola",
    "Pimburattewa",
    "Pulastigama",
    "Ranamuregama",
    "Rattota",
    "Selagama",
    "Sigiriya",
    "Sinhagama",
    "Sungavila",
    "Talagoda Junction",
    "Talakiriyagama",
    "Tamankaduwa",
    "Udasgiriya",
    "Udatenna",
    "Ukuwela",
    "Wahacotte",
    "Walawela",
    "Wehigala",
    "Welangahawatte",
    "Wewalawewa",
    "Yatawatta"
  ],
  "Matara": [
    "Akuressa",
    "Alapaladeniya",
    "Aparekka",
    "Athuraliya",
    "Bengamuwa",
    "Bopagoda",
    "Dampahala",
    "Deegala Lenama",
    "Deiyandara",
    "Denagama",
    "Denipitiya",
    "Deniyaya",
    "Derangala",
    "Devinuwara (Dondra)",
    "Dikwella",
    "Diyagaha",
    "Diyalape",
    "Gandara",
    "Godapitiya",
    "Gomilamawarala",
    "Hawpe",
    "Horapawita",
    "Kalubowitiyana",
    "Kamburugamuwa",
    "Kamburupitiya",
    "Karagoda Uyangoda",
    "Karaputugala",
    "Karatota",
    "Karatota",
    "Kekanadura",
    "Kiriweldola",
    "Kiriwelkele",
    "Kolawenigama",
    "Kotapola",
    "Lankagama",
    "Makandura",
    "Maliduwa",
    "Maramba",
    "Matara",
    "Mediripitiya",
    "Miella",
    "Mirissa",
    "Morawaka",
    "Mulatiyana Junction",
    "Nadugala",
    "Naimana",
    "Palatuwa",
    "Parapamulla",
    "Pasgoda",
    "Penetiyana",
    "Pitabeddara",
    "Puhulwella",
    "Radawela",
    "Ransegoda",
    "Rotumba",
    "Sultanagoda",
    "Telijjawila",
    "Thihagoda",
    "Urubokka",
    "Urugamuwa",
    "Urumutta",
    "Viharahena",
    "Walakanda",
    "Walasgala",
    "Waralla",
    "Weligama",
    "Wilpita",
    "Yatiyana"
  ],
  "Monaragala": [
    "Ayiwela",
    "Badalkumbura",
    "Baduluwela",
    "Bakinigahawela",
    "Balaharuwa",
    "Bibile",
    "Buddama",
    "Buttala",
    "Dambagalla",
    "Diyakobala",
    "Dombagahawela",
    "Ethimalewewa",
    "Ettiliwewa",
    "Galabedda",
    "Gamewela",
    "Hambegamuwa",
    "Hingurukaduwa",
    "Hulandawa",
    "Inginiyagala",
    "Kandaudapanguwa",
    "Kandawinna",
    "Kataragama",
    "Kotagama",
    "Kotamuduna",
    "Kotawehera Mankada",
    "Kudawewa",
    "Kumbukkana",
    "Marawa",
    "Mariarawa",
    "Medagana",
    "Medawelagama",
    "Miyanakandura",
    "Monaragala",
    "Moretuwegama",
    "Nakkala",
    "Namunukula",
    "Nannapurawa",
    "Nelliyadda",
    "Nilgala",
    "Obbegoda",
    "Okkampitiya",
    "Pangura",
    "Pitakumbura",
    "Randeniya",
    "Ruwalwela",
    "Sella Kataragama",
    "Siyambalagune",
    "Siyambalanduwa",
    "Suriara",
    "Thanamalwila",
    "Uva Gangodagama",
    "Uva Kudaoya",
    "Uva Pelwatta",
    "Warunagama",
    "Wedikumbura",
    "Weherayaya Handapanagala",
    "Wellawaya",
    "Wilaoya",
    "Yudaganawa"
  ],
  "Mullaitivu": [
    "Alampil",
    "Ampalavanpokkanai",
    "Ananthapuram",
    "Ethawetunuwewa",
    "Karuppaddamurippu",
    "Kokkilai",
    "Kokkuthuoduvai",
    "Kumulamunai",
    "Mankulam",
    "Mullathivu",
    "Mullativu",
    "Mullivaikkal",
    "Mulliyawalai",
    "Murukandy",
    "Muththaiyankaddukulam",
    "Naddankandal",
    "Oddusudan",
    "Puthukkudiyiruppu",
    "Puthuvedduvan",
    "Thunukkai",
    "Udayarkaddu",
    "Vavunakkulam",
    "Visvamadukulam",
    "Welioya",
    "Yogapuram"
  ],
  "Polonnaruwa": [
    "Attanakadawala",
    "Bakamuna",
    "Diyabeduma",
    "Elahera",
    "Giritale",
    "Hingurakdamana",
    "Hingurakgoda",
    "Jayanthipura",
    "Kalingaela",
    "Lakshauyana",
    "Mankemi",
    "Minneriya",
    "Onegama",
    "Orubendi Siyambalawa",
    "Palugasdamana",
    "Panichankemi",
    "Polonnaruwa",
    "Talpotha",
    "Tambala",
    "Unagalavehera",
    "Wijayabapura"
  ],
  "Puttalam": [
    "Adippala",
    "Alutgama",
    "Alutwewa",
    "Ambakandawila",
    "Anamaduwa",
    "Andigama",
    "Angunawila",
    "Attawilluwa",
    "Bangadeniya",
    "Baranankattuwa",
    "Battuluoya",
    "Bujjampola",
    "Chilaw",
    "Dalukana",
    "Dankotuwa",
    "Dewagala",
    "Dummalasuriya",
    "Dunkannawa",
    "Eluwankulama",
    "Ettale",
    "Galamuna",
    "Galmuruwa",
    "Hansayapalama",
    "Ihala Kottaramulla",
    "Ilippadeniya",
    "Inginimitiya",
    "Ismailpuram",
    "Jayasiripura",
    "Kakkapalliya",
    "Kalkudah",
    "Kalladiya",
    "Kandakuliya",
    "Karathivu",
    "Karawitagara",
    "Karuwalagaswewa",
    "Katuneriya",
    "Koswatta",
    "Kottantivu",
    "Kottapitiya",
    "Kottukachchiya",
    "Kumarakattuwa",
    "Kurinjanpitiya",
    "Kuruketiyawa",
    "Lunuwila",
    "Madampe",
    "Madurankuliya",
    "Mahakumbukkadawala",
    "Mahauswewa",
    "Mampitiya",
    "Mampuri",
    "Mangalaeliya",
    "Marawila",
    "Mudalakkuliya",
    "Mugunuwatawana",
    "Mukkutoduwawa",
    "Mundel",
    "Muttibendiwila",
    "Nainamadama",
    "Nalladarankattuwa",
    "Nattandiya",
    "Nawagattegama",
    "Nelumwewa",
    "Norachcholai",
    "Pallama",
    "Palliwasalturai",
    "Panirendawa",
    "Parakramasamudraya",
    "Pothuwatawana",
    "Puttalam",
    "Puttalam Cement Factory",
    "Rajakadaluwa",
    "Saliyawewa Junction",
    "Serukele",
    "Siyambalagashene",
    "Tabbowa",
    "Talawila Church",
    "Toduwawa",
    "Udappuwa",
    "Uridyawa",
    "Vanathawilluwa",
    "Waikkal",
    "Watugahamulla",
    "Wennappuwa",
    "Wijeyakatupotha",
    "Wilpotha",
    "Yodaela",
    "Yogiyana"
  ],
  "Ratnapura": [
    "Akarella",
    "Amunumulla",
    "Atakalanpanna",
    "Ayagama",
    "Balangoda",
    "Batatota",
    "Beralapanathara",
    "Bogahakumbura",
    "Bolthumbe",
    "Bomluwageaina",
    "Bowalagama",
    "Bulutota",
    "Dambuluwana",
    "Daugala",
    "Dela",
    "Delwala",
    "Dodampe",
    "Doloswalakanda",
    "Dumbara Manana",
    "Eheliyagoda",
    "Ekamutugama",
    "Elapatha",
    "Ellagawa",
    "Ellaulla",
    "Ellawala",
    "Embilipitiya",
    "Eratna",
    "Erepola",
    "Gabbela",
    "Gangeyaya",
    "Gawaragiriya",
    "Gillimale",
    "Godakawela",
    "Gurubewilagama",
    "Halwinna",
    "Handagiriya",
    "Hatangala",
    "Hatarabage",
    "Hewanakumbura",
    "Hidellana",
    "Hiramadagama",
    "Horewelagoda",
    "Imaduwa",
    "Imbulpe",
    "Ittakanda",
    "Kahangama",
    "Kahawatta",
    "Kalawana",
    "Kaltota",
    "Kalubululanda",
    "Kananke Bazaar",
    "Kandepuhulpola",
    "Karandana",
    "Karangoda",
    "Kella Junction",
    "Keppetipola",
    "Kiriella",
    "Kiriibbanwewa",
    "Kolambage Ara",
    "Kolombugama",
    "Kolonna",
    "Kudawa",
    "Kuruwita",
    "Lellopitiya",
    "Mahagama Colony",
    "Mahawalatenna",
    "Makandura",
    "Malwala Junction",
    "Malwatta",
    "Matuwagalagama",
    "Medagalature",
    "Meddekanda",
    "Minipura Dumbara",
    "Mitipola",
    "Moragala Kirillapone",
    "Morahela",
    "Mulendiyawala",
    "Mulgama",
    "Nawalakanda",
    "Nawinnapinnakanda",
    "Niralagama",
    "Nivitigala",
    "Omalpe",
    "Opanayaka",
    "Padalangala",
    "Pallebedda",
    "Pallekanda",
    "Pambagolla",
    "Panamura",
    "Panapola",
    "Paragala",
    "Parakaduwa",
    "Pebotuwa",
    "Pelmadulla",
    "Pinnawala",
    "Pothdeniya",
    "Rajawaka",
    "Ranwala",
    "Rassagala",
    "Rathgama",
    "Ratna Hangamuwa",
    "Ratnapura",
    "Sewanagala",
    "Sri Palabaddala",
    "Sudagala",
    "Thalakolahinna",
    "Thanjantenna",
    "Theppanawa",
    "Thunkama",
    "Udakarawita",
    "Udaniriella",
    "Udawalawe",
    "Ullinduwawa",
    "Veddagala",
    "Vijeriya",
    "Waleboda",
    "Watapotha",
    "Waturawa",
    "Weligepola",
    "Welipathayaya",
    "Wikiliya"
  ],
  "Trincomalee": [
    "Agbopura",
    "Buckmigama",
    "China Bay",
    "Dehiwatte",
    "Echchilampattai",
    "Galmetiyawa",
    "Gomarankadawala",
    "Kaddaiparichchan",
    "Kallar",
    "Kanniya",
    "Kantalai",
    "Kantalai Sugar Factory",
    "Kiliveddy",
    "Kinniya",
    "Kuchchaveli",
    "Kumburupiddy",
    "Kurinchakerny",
    "Lankapatuna",
    "Mahadivulwewa",
    "Maharugiramam",
    "Mallikativu",
    "Mawadichenai",
    "Mullipothana",
    "Mutur",
    "Neelapola",
    "Nilaveli",
    "Pankulam",
    "Pulmoddai",
    "Rottawewa",
    "Sampaltivu",
    "Sampoor",
    "Serunuwara",
    "Seruwila",
    "Sirajnagar",
    "Somapura",
    "Tampalakamam",
    "Thuraineelavanai",
    "Tiriyayi",
    "Toppur",
    "Trincomalee",
    "Wanela"
  ],
  "Vavuniya": [
    "Alagalla",
    "Andiyapuliyankulam",
    "Asikulam",
    "Cheddikulam",
    "Chemamadukulam",
    "Iranai lluppaikulam",
    "Iratta Periyakulama",
    "Kalmadhu",
    "Kanagarayankulam",
    "Kannaddi",
    "Kela Bogaswewa",
    "Kovilkulam",
    "Madukanda",
    "Mahakachchakodiya",
    "Mamaduwa",
    "Maradammaduwa",
    "Maraiyadithakulam",
    "Maruthodai",
    "Mathavuvaithakulam",
    "Nainamadu",
    "Nedunkerny",
    "Nelukkulam",
    "Neriyakulam",
    "Nochchimoddai",
    "Omanthai",
    "Palamoddai",
    "Pampaimadu",
    "Pavakkulama Unit 1",
    "Pavakkulama Unit 2",
    "Periya Ulukkulama",
    "Periyathambanai",
    "Poovarasankulam",
    "Puliyankulam",
    "Sathirikulankulam",
    "Sinnasippikulam",
    "Thandikulam",
    "Vaarikkuttiyoor",
    "Vavuniya"
  ]
};

export default function IgnoreRoute() { return null; }
